### ISSUE TITLE
Add to the official Chataigne community module list ?

### ISSUE THREAD

**Issue by benkuper** [alex-Arc/Ontime-Chataigne-module#1]
Hello,
just got the creator of ontime on the Chataigne discord server asking for helping on a chataigne module, seems like this would be a great place to have a unified dev.

If you wish to have it as an official community module , please let me know or even better you can create a pull request in the https://github.com/benkuper/Chataigne-community-modules repository

Cheers !

**Comment by alex-Arc** [comment]
thank you
we have all the main features covered now
https://github.com/benkuper/Chataigne-community-modules/pull/12
